[package]
name = "airsense"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bosch-bme680 = "1.0.2"
linux-embedded-hal = "0.4.0"
